/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import model.Town;
import model.Community;
import model.Address;
import model.Person;

/**
 *
 * @author vagishadeo
 */
public class EnterPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterPersonJPanel
     */
    private Town town;
    
    public EnterPersonJPanel(Town town)
    {
        initComponents();
        this.town = town;
        CityDropdown.addItem(town);
        town.getcommunityArray().forEach(community -> CommunityDropdown.addItem(community));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        AgeTextF = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CommunityLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        CityDropdown = new javax.swing.JComboBox<>();
        CommunityDropdown = new javax.swing.JComboBox<>();
        AddressDropdown = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        PersonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PersonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonLabel.setText("Enter person information");

        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        NameLabel.setText("Person Name");

        AgeLabel.setText("Person Age");

        CityLabel.setText("Person's City");

        CommunityLabel.setText("Community:");

        AddressLabel.setText("Address:");

        CityDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityDropdownActionPerformed(evt);
            }
        });

        CommunityDropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CommunityDropdownItemStateChanged(evt);
            }
        });
        CommunityDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityDropdownActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PersonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CommunityLabel)
                                    .addComponent(CityLabel)
                                    .addComponent(AgeLabel)
                                    .addComponent(NameLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AddressLabel)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AgeTextF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CommunityDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddressDropdown, 0, 201, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommunityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(SaveButton)
                .addContainerGap(411, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if(NameText == null || "".equals(NameText.getText().trim())
                || !Pattern.matches("^(?![\\s.]+$)[a-zA-Z\\s.]*$", NameText.getText())) {
            showMessageDialog(this, "Please enter valid name", "Error", ERROR_MESSAGE);
            return;
        }
        else if(AgeTextF == null || "".equals(AgeTextF.getText().trim()) 
                || !Pattern.matches("^[0-9]{1,2}$", AgeTextF.getText().trim())) {
            showMessageDialog(this, "Please enter valid age", "Error", ERROR_MESSAGE);
            return;
        }
        String name = NameText.getText();
        String age = AgeTextF.getText();
        Address house = (Address) AddressDropdown.getSelectedItem();
        Person person = house.enterPerson();
        person.setperson_name(name);
        person.setperson_age(age);
        JOptionPane.showMessageDialog(this, "Person detail entered");
        NameText.setText("");
        AgeTextF.setText("");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CommunityDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityDropdownActionPerformed

    private void CommunityDropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CommunityDropdownItemStateChanged
        AddressDropdown.removeAllItems();
        Community community = (Community) CommunityDropdown.getSelectedItem();
        community.getaddressList().forEach(house -> AddressDropdown.addItem(house));
    }//GEN-LAST:event_CommunityDropdownItemStateChanged

    private void CityDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityDropdownActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<model.Address> AddressDropdown;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTextF;
    private javax.swing.JComboBox<Town> CityDropdown;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JComboBox<Community> CommunityDropdown;
    private javax.swing.JLabel CommunityLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel PersonLabel;
    private javax.swing.JButton SaveButton;
    // End of variables declaration//GEN-END:variables
}
